[server]
enableStaticServing = false

[theme]
base = "light"
primaryColor = "#1a9e8f"
primaryColor = "#1457A8"
backgroundColor = "#f7fbff"
secondaryBackgroundColor = "#edf4ff"
textColor = "#1f2f46"
font = "sans serif"
